# packages in environment at /Users/john/miniconda3:
#
abstract-rendering        0.5.1               np110py35_0    defaults
alabaster                 0.7.6                    py35_0    defaults
anaconda                  2.4.0               np110py35_0    defaults
anaconda-build            0.13.1                   py35_0    defaults
anaconda-client           1.1.0                    py35_0    defaults
appnope                   0.1.0                    py35_0    defaults
appscript                 1.0.1                    py35_0    defaults
argcomplete               1.0.0                    py35_1    defaults
astropy                   1.0.5               np110py35_1    defaults
babel                     2.1.1                    py35_0    defaults
beautifulsoup4            4.4.1                    py35_0    defaults
bitarray                  0.8.1                    py35_0    defaults
blaze                     0.8.3                     <pip>
blaze-core                0.8.3                    py35_0    defaults
bokeh                     0.10.0                   py35_0    defaults
boto                      2.38.0                   py35_0    defaults
cffi                      1.3.1                         0    johntfoster
clyent                    0.4.0                    py35_0    defaults
colorama                  0.3.3                    py35_0    defaults
conda                     3.19.1                   py35_0    defaults
conda-build               1.18.1                   py35_0    defaults
conda-env                 2.4.5                    py35_0    defaults
configobj                 5.0.6                    py35_0    defaults
cryptography              1.0.2                    py35_0    defaults
curl                      7.45.0                        0    defaults
cython                    0.23.4                   py35_0    defaults
cytoolz                   0.7.4                    py35_0    defaults
datashape                 0.4.7               np110py35_1    defaults
decorator                 4.0.4                    py35_0    defaults
docutils                  0.12                     py35_0    defaults
fastcache                 1.0.2                    py35_0    defaults
flask                     0.10.1                   py35_1    defaults
flexx                     0.2                      py35_0    bokeh
freetype                  2.5.5                         0    defaults
greenlet                  0.4.9                    py35_0    defaults
h5py                      2.5.0               np110py35_4    defaults
idna                      2.0                      py35_0    defaults
ipykernel                 4.1.1                    py35_0    defaults
ipython                   4.0.0                    py35_1    defaults
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py35_0    defaults
ipython-qtconsole         4.0.1                    py35_0    defaults
ipython_genutils          0.1.0                    py35_0    defaults
ipywidgets                4.1.0                    py35_0    defaults
itsdangerous              0.24                     py35_0    defaults
jdcal                     1.0                      py35_0    defaults
jedi                      0.9.0                    py35_0    defaults
jinja2                    2.8                      py35_0    defaults
jpeg                      8d                            1    defaults
jsonschema                2.4.0                    py35_0    defaults
jupyter                   1.0.0                    py35_0    defaults
jupyter-client            4.1.1                     <pip>
jupyter-console           4.0.3                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py35_0    defaults
jupyter_console           4.0.3                    py35_0    defaults
jupyter_core              4.0.6                    py35_0    defaults
launcher                  1.0.0                         3    defaults
libffi                    3.0.13                        0    johntfoster
libpng                    1.6.17                        0    defaults
libtiff                   4.0.6                         0    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        2    defaults
lxml                      3.4.4                    py35_0    defaults
markdown                  2.6.5                     <pip>
markupsafe                0.23                     py35_0    defaults
matplotlib                1.4.3               np110py35_3    defaults
mistune                   0.7.1                    py35_0    defaults
multipledispatch          0.4.8                    py35_0    defaults
nbconvert                 4.0.0                    py35_0    defaults
nbformat                  4.0.1                    py35_0    defaults
networkx                  1.10                     py35_0    defaults
nltk                      3.1                      py35_0    defaults
node-webkit               0.10.1                        0    defaults
nose                      1.3.7                    py35_0    defaults
notebook                  4.0.6                    py35_0    defaults
numexpr                   2.4.4               np110py35_0    defaults
numpy                     1.10.1                   py35_0    defaults
odo                       0.3.4                    py35_0    defaults
openblas                  0.2.14                        3    defaults
openpyxl                  2.2.6                    py35_0    defaults
openssl                   1.0.2f                        0    defaults
pandas                    0.17.0              np110py35_0    defaults
path.py                   8.1.2                    py35_0    defaults
patsy                     0.4.0               np110py35_0    defaults
pep8                      1.6.2                    py35_0    defaults
pexpect                   3.3                      py35_0    defaults
pickleshare               0.5                      py35_0    defaults
pillow                    3.0.0                    py35_1    defaults
pip                       8.0.2                    py35_0    defaults
ply                       3.8                      py35_0    defaults
powerline-status          2.3                       <pip>
psutil                    3.2.2                    py35_0    defaults
ptyprocess                0.5                      py35_0    defaults
py                        1.4.30                   py35_0    defaults
pyasn1                    0.1.9                    py35_0    defaults
pycosat                   0.6.1                    py35_0    defaults
pycparser                 2.14                     py35_0    defaults
pycrypto                  2.6.1                    py35_0    defaults
pycurl                    7.19.5.1                 py35_3    defaults
pyflakes                  1.0.0                    py35_0    defaults
pygments                  2.0.2                    py35_0    defaults
pyopenssl                 0.15.1                   py35_1    defaults
pyparsing                 2.0.3                    py35_0    defaults
pyqt                      4.11.4                   py35_0    defaults
pytables                  3.2.2               np110py35_0    defaults
pytest                    2.8.1                    py35_0    defaults
python                    3.5.1                         0    defaults
python-dateutil           2.4.2                    py35_0    defaults
python.app                1.2                      py35_4    defaults
pytz                      2015.6                   py35_0    defaults
pyyaml                    3.11                     py35_1    defaults
pyzmq                     14.7.0                   py35_1    defaults
qt                        4.8.7                         1    defaults
qtconsole                 4.1.0                    py35_0    defaults
readline                  6.2                           2    defaults
redis                     2.6.9                         0    defaults
redis-py                  2.10.3                   py35_0    defaults
requests                  2.9.1                    py35_0    defaults
rope                      0.9.4                    py35_1    defaults
rope-py3k                 0.9.4.post1               <pip>
scikit-image              0.11.3              np110py35_0    defaults
scikit-learn              0.16.1              np110py35_0    defaults
scipy                     0.16.0              np110py35_1    defaults
setuptools                19.6.2                   py35_0    defaults
simplegeneric             0.8.1                    py35_0    defaults
sip                       4.16.9                   py35_0    defaults
six                       1.10.0                   py35_0    defaults
snowballstemmer           1.2.0                    py35_0    defaults
sockjs-tornado            1.0.1                    py35_0    defaults
sphinx                    1.3.1                    py35_0    defaults
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py35_0    defaults
spyder                    2.3.7                    py35_1    defaults
spyder-app                2.3.7                    py35_0    defaults
sqlalchemy                1.0.9                    py35_0    defaults
sqlite                    3.9.2                         0    defaults
statsmodels               0.6.1               np110py35_0    defaults
sympy                     0.7.6.1                  py35_0    defaults
tables                    3.2.2                     <pip>
terminado                 0.5                      py35_1    defaults
tk                        8.5.18                        0    defaults
toolz                     0.7.4                    py35_0    defaults
tornado                   4.2.1                    py35_1    defaults
traitlets                 4.0.0                    py35_0    defaults
ujson                     1.33                     py35_0    defaults
unicodecsv                0.14.1                   py35_0    defaults
werkzeug                  0.10.4                   py35_0    defaults
wheel                     0.26.0                   py35_1    defaults
xlrd                      0.9.4                    py35_0    defaults
xlsxwriter                0.7.7                    py35_0    defaults
xlwings                   0.4.1                    py35_0    defaults
xlwt                      1.0.0                    py35_0    defaults
xz                        5.0.5                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.3                         0    defaults
zlib                      1.2.8                      py27    file:///Users/john/miniconda3/conda-bld/osx-64/zlib-1.2.8-py27.tar.bz2
